// This file contains the JSON data of 50 students with their marks in four subjects: maths, english, physics, and chemistry. The data is stored in an array of objects. Each object represents a student and contains the following properties:{
export const students = [
  {
    name: "Alice",
    gender: "female",
    maths: 85,
    english: 78,
    physics: 92,
    chemistry: 88,
  },
  {
    name: "brandy",
    gender: "female",
    maths: 45,
    english: 76,
    physics: 54,
    chemistry: 76,
  },
  {
    name: "sandy",
    gender: "female",
    maths: 90,
    english: 30,
    physics: 42,
    chemistry: 54,
  },
  {
    name: "Bob",
    gender: "male",
    maths: 72,
    english: 85,
    physics: 78,
    chemistry: 80,
  },
  {
    name: "Charlie",
    gender: "male",
    maths: 90,
    english: 88,
    physics: 85,
    chemistry: 75,
  },
  {
    name: "Diana",
    gender: "female",
    maths: 68,
    english: 76,
    physics: 82,
    chemistry: 70,
  },
  {
    name: "Eva",
    gender: "female",
    maths: 95,
    english: 90,
    physics: 88,
    chemistry: 92,
  },
  {
    name: "Frank",
    gender: "male",
    maths: 80,
    english: 82,
    physics: 75,
    chemistry: 78,
  },
  {
    name: "Grace",
    gender: "female",
    maths: 82,
    english: 88,
    physics: 85,
    chemistry: 80,
  },
  {
    name: "Henry",
    gender: "male",
    maths: 78,
    english: 75,
    physics: 70,
    chemistry: 68,
  },
  {
    name: "Ivy",
    gender: "female",
    maths: 90,
    english: 92,
    physics: 88,
    chemistry: 90,
  },
  {
    name: "Jack",
    gender: "male",
    maths: 85,
    english: 80,
    physics: 82,
    chemistry: 78,
  },
  {
    name: "Kelly",
    gender: "female",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 68,
  },
  {
    name: "Leo",
    gender: "male",
    maths: 92,
    english: 88,
    physics: 90,
    chemistry: 85,
  },
  {
    name: "Mia",
    gender: "female",
    maths: 80,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "Nathan",
    gender: "male",
    maths: 70,
    english: 72,
    physics: 68,
    chemistry: 65,
  },
  {
    name: "Olivia",
    gender: "female",
    maths: 88,
    english: 92,
    physics: 85,
    chemistry: 90,
  },
  {
    name: "Peter",
    gender: "male",
    maths: 75,
    english: 80,
    physics: 72,
    chemistry: 68,
  },
  {
    name: "Quinn",
    gender: "female",
    maths: 78,
    english: 82,
    physics: 75,
    chemistry: 70,
  },
  {
    name: "Ryan",
    gender: "male",
    maths: 82,
    english: 85,
    physics: 80,
    chemistry: 78,
  },
  {
    name: "Sophia",
    gender: "female",
    maths: 90,
    english: 95,
    physics: 88,
    chemistry: 92,
  },
  {
    name: "Tom",
    gender: "male",
    maths: 68,
    english: 72,
    physics: 65,
    chemistry: 60,
  },
  {
    name: "Uma",
    gender: "female",
    maths: 78,
    english: 82,
    physics: 75,
    chemistry: 70,
  },
  {
    name: "Vincent",
    gender: "male",
    maths: 85,
    english: 88,
    physics: 82,
    chemistry: 80,
  },
  {
    name: "Wendy",
    gender: "female",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 68,
  },
  {
    name: "Xavier",
    gender: "male",
    maths: 92,
    english: 90,
    physics: 88,
    chemistry: 85,
  },
  {
    name: "Yara",
    gender: "female",
    maths: 80,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "Zack",
    gender: "male",
    maths: 70,
    english: 75,
    physics: 68,
    chemistry: 65,
  },
  {
    name: "Amelia",
    gender: "female",
    maths: 88,
    english: 90,
    physics: 85,
    chemistry: 92,
  },
  {
    name: "Ben",
    gender: "male",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 70,
  },
  {
    name: "Chloe",
    gender: "female",
    maths: 82,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "David",
    gender: "male",
    maths: 90,
    english: 92,
    physics: 88,
    chemistry: 90,
  },
  {
    name: "Emma",
    gender: "female",
    maths: 68,
    english: 72,
    physics: 65,
    chemistry: 60,
  },
  {
    name: "Finn",
    gender: "male",

    maths: 78,
    english: 82,
    physics: 75,
    chemistry: 70,
  },
  {
    name: "Gabrielle",
    gender: "female",
    maths: 85,
    english: 88,
    physics: 82,
    chemistry: 80,
  },
  {
    name: "Harry",
    gender: "male",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 68,
  },
  {
    name: "Isabel",
    gender: "female",
    maths: 92,
    english: 90,
    physics: 88,
    chemistry: 85,
  },
  {
    name: "John",
    gender: "male",
    maths: 80,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "Kate",
    gender: "female",
    maths: 70,
    english: 75,
    physics: 68,
    chemistry: 65,
  },
  {
    name: "Liam",
    gender: "male",
    maths: 88,
    english: 90,
    physics: 85,
    chemistry: 92,
  },
  {
    name: "Molly",
    gender: "female",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 70,
  },
  {
    name: "Nate",
    gender: "male",
    maths: 82,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "Oliver",
    gender: "male",
    maths: 90,
    english: 92,
    physics: 88,
    chemistry: 85,
  },
  {
    name: "Penny",
    gender: "female",
    maths: 68,
    english: 72,
    physics: 65,
    chemistry: 60,
  },
  {
    name: "Quentin",
    gender: "male",
    maths: 78,
    english: 82,
    physics: 75,
    chemistry: 70,
  },
  {
    name: "Rachel",
    gender: "female",
    maths: 85,
    english: 88,
    physics: 82,
    chemistry: 80,
  },
  {
    name: "Sam",
    gender: "male",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 68,
  },
  {
    name: "Tina",
    gender: "female",
    maths: 92,
    english: 90,
    physics: 88,
    chemistry: 85,
  },
  {
    name: "Ulysses",
    gender: "male",
    maths: 80,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "Violet",
    gender: "female",
    maths: 70,
    english: 75,
    physics: 68,
    chemistry: 65,
  },
  {
    name: "William",
    gender: "male",
    maths: 88,
    english: 90,
    physics: 85,
    chemistry: 92,
  },
  {
    name: "Xander",
    gender: "male",
    maths: 75,
    english: 78,
    physics: 72,
    chemistry: 70,
  },
  {
    name: "Yolanda",
    gender: "female",
    maths: 82,
    english: 85,
    physics: 78,
    chemistry: 75,
  },
  {
    name: "Zoe",
    gender: "female",
    maths: 90,
    english: 92,
    physics: 88,
    chemistry: 85,
  },
];
